[settings]
bot_name = "your friendly neighborhood penguin, ocfbot"
contact_info = "https://github.com/ocf/adelie"
dry_run = false

[[repo]]
github_id = "ocf/badgr"

  [[repo.software]]
  name = "badgr"
  changelog = "https://github.com/concentricsky/badgr-server/releases/tag/v{0}"
  file = "Makefile"
  regex = "(?<=API_VERSION := v)(.*)(?=\n)"
  type = "relmon"
  id = "127518"

[[repo]]
github_id = "ocf/fava"

  [[repo.software]]
  name = "fava"
  changelog = "https://github.com/beancount/fava/blob/master/CHANGES"
  file = "kubernetes/fava.yml.erb"
  regex = "(?<=image: \"yegle/fava:version-)(.*)(?=\")"
  type = "relmon"
  id = "51418"

[[repo]]
github_id = "ocf/grafana"

  [[repo.software]]
  name = "grafana"
  changelog = "https://github.com/grafana/grafana/releases/tag/v{0}"
  file = "Makefile"
  regex = "(?<=GF_VERSION := )(.*)(?=\n)"
  type = "relmon"
  id = "13916"

[[repo]]
github_id = "ocf/kafka"

  [[repo.software]]
  name = "kafka"
  changelog = "https://downloads.apache.org/kafka/{0}/RELEASE_NOTES.html"
  file = "Dockerfile"
  regex = "(?<=KAFKA_VERSION=)(.*)(?=\n)"
  type = "relmon"
  id = "125089"
  filter = "rc"

[[repo]]
github_id = "ocf/keycloak"

  [[repo.software]]
  name = "keycloak"
  changelog = "https://www.keycloak.org/docs/latest/release_notes/"
  file = "Makefile"
  regex = "(?<=KEYCLOAK_VERSION := )(.*)(?=\n)"
  type = "relmon"
  id = "20430"

[[repo]]
github_id = "ocf/sourcegraph"

  [[repo.software]]
  name = "sourcegraph"
  changelog = "https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md"
  file = "kubernetes/sourcegraph.yaml.erb"
  regex = "(?<=image: \"sourcegraph/server:)(.*)(?=\")"
  type = "relmon"
  id = "126322"
  filter = "rc"

[[repo]]
github_id = "ocf/matrix"

  [[repo.software]]
  name = "synapse"
  changelog = "https://github.com/matrix-org/synapse/releases/tag/v{0}"
  file = "Makefile"
  regex = "(?<=SYNAPSE_VERSION := v)(.*)(?=\n)"
  type = "relmon"
  id = "15283"
  filter = "rc"

  [[repo.software]]
  name = "element"
  changelog = "https://github.com/vector-im/element-web/releases/tag/v{0}"
  file = "Makefile"
  regex = "(?<=RIOT_VERSION := v)(.*)(?=\n)"
  type = "relmon"
  id = "18626"
  filter = "rc"

  [[repo.software]]
  name = "bridge"
  changelog = "https://github.com/matrix-org/matrix-appservice-irc/releases/tag/{0}"
  file = "Makefile"
  regex = "(?<=BRIDGE_VERSION := release-)(.*)(?=\n)"
  type = "relmon"
  id = "121056"
  filter = "rc"

[[repo]]
github_id = "ocf/snipe-it"

  [[repo.software]]
  name = "snipe-it"
  changelog = "https://github.com/snipe/snipe-it/releases/tag/v{0}"
  file = "kubernetes/snipe-it.yaml"
  regex = "(?<=image: \"snipe/snipe-it:v)(.*)(?=\")"
  type = "relmon"
  id = "124519"
  filter = "beta"

[[repo]]
github_id = "ocf/thelounge"

  [[repo.software]]
  name = "thelounge"
  changelog = "https://github.com/thelounge/thelounge/releases/tag/v{0}"
  file = "Dockerfile"
  regex = "(?<=FROM thelounge/thelounge:)(.*)(?=\n)"
  type = "npm"
  id = "thelounge"

[[repo]]
github_id = "ocf/pma"

  [[repo.software]]
  name = "phpmyadmin"
  changelog = "https://www.phpmyadmin.net/files/{0}"
  file = "Makefile"
  regex = "(?<=PMA_VERSION := )(.*)(?=\n)"
  type = "relmon"
  id = "3628"
